# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_user_psid', models.CharField(blank=True, max_length=1000)),
                ('fb_user_first_name', models.CharField(blank=True, max_length=1000)),
                ('fb_user_last_name', models.CharField(blank=True, max_length=1000)),
                ('fb_user_profile_pic', models.CharField(blank=True, max_length=1000)),
                ('fb_user_locale', models.CharField(blank=True, max_length=1000)),
                ('fb_user_gender', models.CharField(blank=True, max_length=1000)),
                ('fb_user_timezone', models.CharField(blank=True, max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
