# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
